apiVersion: v1
kind: Pod
metadata:
  name: csvolume
spec:
  containers:
  - name: busybox
    image: busybox
    command : ["sh", "-c" ,'while true ;do sleep 3000; done']
    volumeMounts:
      - name : myvolume
        mountPath: /config 
  volumes:
    - name: myvolume
      configMap:
       name: myapp

    

