apiVersion: apps/v1
kind: Deployment
metadata:
  name: myappwewdeploy
spec:
  replicas: 6
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: mynginx
        image: nginx
