apiVersion: v1
kind: Pod
metadata: 
  name: bluepod
spec:
 nodeSelector: 
  colour: bule
 containers:
 - name: n1
   image: nginx
 tolerations:
 - key: "colour"
   operator: "Equal"
   value: "bule"
   effect: "NoSchedule"
  
---
apiVersion: v1
kind: Pod
metadata: 
  name: greenpod
spec:
 nodeSelector: 
  colour: green
 containers:
 - name: n1
   image: nginx
 tolerations:
 - key: "colour"
   operator: "Equal"
   value: "green"
   effect: "NoSchedule"

---
apiVersion: v1
kind: Pod
metadata: 
  name: orangepod
spec:
 nodeSelector: 
  colour: orange
 containers:
 - name: n1
   image: nginx
 tolerations:
 - key: "colour"
   operator: "Equal"
   value: "orange"
   effect: "NoSchedule"   