apiVersion: v1
kind: Pod
metadata:
  name: burstable
  labels:
    name: myapp
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "100Mi"
        cpu: "100m"
      requests:
       memory: "200mi"
       cpu: "200m"    
    