apiVersion: v1
kind: Pod
metadata:
  name: myapp
spec:
  containers:
  - name: myapp
    image: busybox
    command : [ "sh", "-c" ," echo configmap is $configvalue and secret is $Secretcode  && sleep 30"]
    env:
     - name : configvalue
       valueFrom :
        configMapKeyRef: 
         name : myapp
         key : name
     - name : Secretcode
       valueFrom: 
        secretKeyRef:
          name : mysecret
          key : password     
         