apiVersion: v1
kind: Pod
metadata:
  name: burstable
  labels:
    name: myapp
spec:
  containers:
  - name: nginx
    image: nginx
    resources: 
      requests:
       memory: "100mi"
       cpu: "100m" 
      limits:
        memory: "100Mi"
        cpu: "100m"    
    