apiVersion: v1
kind: Service
metadata:
  name: livenessfailure
spec:
  selector:
    name: myapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
  livenessProbe:
   httpGet:
    path: /vinay
    port: 80
   initialDelaySeconds: 10
   periodSeconds: 10 
   
