apiVersion: v1
kind: Pod
metadata:
  name: livenesssucess
spec:
 containers:
 - image: nginx
   name : nginx
   livenessProbe:
    httpGet:
     path: /
     port: 80
    initialDelaySeconds: 10
    periodSeconds: 10 
   
