apiVersion: v1
kind: Pod
metadata:
 name: livenesspod 
spec:
 containers:
 - name : busybox
   image: busybox 
   command : ["sh", "-c", " echo liveness probe && sleep 360"]
   livenessProbe:
    exec : 
      command: ["echo", "pod is alive"]
    initialDelaySeconds: 10
