apiVersion: v1
kind: Pod
metadata:
  name: livenesssucesss
  labels:
   app : myapp
spec:
 containers:
 - image: nginx
   name : nginx
   livenessProbe:
    httpGet:
     path: /
     port: 80
    initialDelaySeconds: 10
    periodSeconds: 10 
   readinessProbe:
     httpGet:
      path: /
      port: 80
     initialDelaySeconds: 10
     periodSeconds: 10  
     
---

apiVersion: v1
kind: Service
metadata:
  name: liveready
spec:
  selector:
    name: myapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

   
