apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
spec:
  replicas: 3   ## create 3 pods based on templates
  template:     ## template contains information of pod 
    metadata:
      name: myapp   #The name of the pod template is myapp.
      labels:            # lables for pod (rc)
        env: test
        dc: hyd
    spec:            # specification for pod and should be under template
      containers:
        - name: firstapp
          image: nginx
          
