apiVersion: v1
kind: Pod
metadata:
  name: rro
spec:
  volumes:
    - name: mnt
      hostPath:
        # tmpfs is mounted on /mnt/tmpfs
        path: /mnt
  replicas: 3      
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c"]
      args: ["echo testing !!! > /mnt-rw/success.txt && sleep infinity"]
      volumeMounts:
        # /mnt-rro/tmpfs is not writable
        - name: mnt
          mountPath: /mnt-rro
          readOnly: true
          mountPropagation: None
        # /mnt-ro/tmpfs is writable
        - name: mnt
          mountPath: /mnt-ro
          readOnly: false
        # /mnt-rw/tmpfs is writable
        - name: mnt
          mountPath: /mnt-rw
          readOnly: false

