apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxdeploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      version: blues
  template:
    metadata:
      labels:
        app: nginx
        version: blues
    spec:  
      containers:
      - name: nginxblue
        image: devopswithcloudhub/nginx:blue
