apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{values.name}}
spec:
  replicas: {{values.replicas.default}}
  selector:
    matchLabels:
      app: nginx
      version: blue
  template:
    metadata:
      labels:
        app: nginx
        version: blue
    spec:  
      containers:
      - name: nginxblue
        image: {{values.image.name}}:{{values.image.tag}}
